### ISSUE TITLE
installation Error

### ISSUE THREAD

**Issue by asaadhoussam** [madcoda9000/dotnet-cookie-based-identity#5]
$ dotnet run
C:\Program Files\dotnet\sdk\6.0.306\Microsoft.Common.CurrentVersion.targets(2302,5): warning MSB3245: Could not resolve this reference
. Could not locate the assembly "DatatableJS.Data". Check to make sure the assembly exists on disk. If this reference is required by y
our code, you may get compilation errors. [D:\aspdotnetcore_ldap\withNovel\dotnet-cookie-based-identity\DotNetIdentity\DotNetIdentity.
csproj]
D:\aspdotnetcore_ldap\withNovel\dotnet-cookie-based-identity\DotNetIdentity\obj\Debug\net6.0\DotNetIdentity.AssemblyInfo.cs(20,12): er
ror CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute [D:\aspdotnetcore_ldap\withNovel\dotnet-cookie-based-iden
tity\DotNetIdentity\DotNetIdentity.csproj]
D:\aspdotnetcore_ldap\withNovel\dotnet-cookie-based-identity\DotNetIdentity\Controllers\AdminController.cs(15,19): error CS0234: The t
ype or namespace name 'Data' does not exist in the namespace 'DatatableJS' (are you missing an assembly reference?) [D:\aspdotnetcore_ 
ldap\withNovel\dotnet-cookie-based-identity\DotNetIdentity\DotNetIdentity.csproj]
D:\aspdotnetcore_ldap\withNovel\dotnet-cookie-based-identity\DotNetIdentity\Controllers\AdminController.cs(116,43): error CS0246: The  
type or namespace name 'DataRequest' could not be found (are you missing a using directive or an assembly reference?) [D:\aspdotnetcor 
e_ldap\withNovel\dotnet-cookie-based-identity\DotNetIdentity\DotNetIdentity.csproj]
D:\aspdotnetcore_ldap\withNovel\dotnet-cookie-based-identity\DotNetIdentity\Controllers\AdminController.cs(135,41): error CS0246: The  
type or namespace name 'DataRequest' could not be found (are you missing a using directive or an assembly reference?) [D:\aspdotnetcor 
e_ldap\withNovel\dotnet-cookie-based-identity\DotNetIdentity\DotNetIdentity.csproj]
D:\aspdotnetcore_ldap\withNovel\dotnet-cookie-based-identity\DotNetIdentity\Controllers\AdminController.cs(153,43): error CS0246: The 
type or namespace name 'DataRequest' could not be found (are you missing a using directive or an assembly reference?) [D:\aspdotnetcor 
e_ldap\withNovel\dotnet-cookie-based-identity\DotNetIdentity\DotNetIdentity.csproj]
D:\aspdotnetcore_ldap\withNovel\dotnet-cookie-based-identity\DotNetIdentity\Controllers\AdminController.cs(171,36): error CS0246: The  
type or namespace name 'DataRequest' could not be found (are you missing a using directive or an assembly reference?) [D:\aspdotnetcor 
e_ldap\withNovel\dotnet-cookie-based-identity\DotNetIdentity\DotNetIdentity.csproj]

The build failed. Fix the build errors and run again.
how to resolve it ? Thanks

**Comment by madcoda9000** [comment]
Hello,

sorry that's my fault. I will update the documentation as soon as possible.

Please do the following:

1. if you're in the DotNetIdentity folder, navigate one folder back by typing `cd ..`
2. then type `cd DatatableJS`
3. the type `dotnet build` and wait until the build is finished
4. navigate back again by typing `cd ..
`5. enter `cd DotNetIdentity`
6. enter `dotnet run` (make sure you've setup appsettings.json as statet in the documentation before!)

Best Regards
Sascha

**Comment by madcoda9000** [comment]
I've updated the INSTALL.md already.
